base_url = "https://paper-zola.pages.dev"
title = "Paper"
description = "Zola Theme"
author = "George Fotopoulos"
compile_sass = false
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "material-light"
render_emoji = true
smart_punctuation = true

[extra]
navbar_items = [
    { title = "Home", url = "/", icon = "home-line" },
    { title = "About", url = "/about/", icon = "user-line" },
    { title = "Posts", url = "/posts/", icon = "article-line" },
    { title = "Projects", url = "/projects/", icon = "flask-line" }
]
social_items = [
    { title = "GitHub", url = "https://github.com/xorz57", icon = "fab fa-github" },
    { title = "LinkedIn", url = "https://www.linkedin.com/in/xorz57", icon = "fab fa-linkedin" }
]
chart = false
katex = false
mapbox_gl = false
mermaid = false

[extra.analytics]
goatcounter = "https://paper-zola.goatcounter.com/count"
